export const GET_ITEMS = 'GET_ITEMS';
export const GET_ITEMS_TO_SHOW= 'GET_ITEMS_TO_SHOW';

export const GET_FILTER = 'GET_FILTER';
export const DELETE_FILTER = 'DELETE_FILTER';
export const GET_TO_FILTER = 'GET_TO_FILTER';
export const GET_NEXT_TO_FILTER = 'GET_NEXT_TO_FILTER';
export const DELETE_FROM_FILTER = 'DELETE_FROM_FILTER';

export const CHANGE_PRICE = 'CHANGE_PRICE';

export const REGISTER_USER = 'REGISTER_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_LOGIN_ERROR = 'GET_LOGIN_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const ADD_TO_CART = 'ADD_TO_CART';