export const GET_ITEMS = 'GET_ITEMS';
export const GET_ITEMS_TO_SHOW= 'GET_ITEMS_TO_SHOW';

export const GET_FILTER = 'GET_FILTER';
export const DELETE_FILTER = 'DELETE_FILTER';
export const GET_TO_FILTER = 'GET_TO_FILTER';
export const GET_NEXT_TO_FILTER = 'GET_NEXT_TO_FILTER';
export const DELETE_FROM_FILTER = 'DELETE_FROM_FILTER';

